import { test } from '@e2e-dev/web';
import { expect } from 'e2e';

test(`tmux survives ordinary links, settings, new-session cancellation and history`, async ({ browser: page, screen, app }) => {
    await page.goto('/e2e-fixtures/workspace-fixture.html?split')
    const shell = page.locator('[data-workspace-ready=true]')
    await expect(shell).toBeVisible({ timeout: 15000 })
    const paneIds = await page.evaluate(() => Array.from(document.querySelectorAll('[data-pane-id][data-session-id]')).map(n => n.getAttribute('data-pane-id')))
    await page.evaluate(() => window.__workspaceFixture.navigate('/sessions/chat-2'))
    await expect(shell).toBeVisible({ timeout: 15000 })
    await expect(page.locator('[data-pane-id][data-session-id="chat-2"]')).toHaveAttribute('data-focused', 'true')
    await page.locator('[data-pane-id][data-session-id="chat-2"] [data-testid="rich-composer-input"]').fill('Keep my tmux draft')
    await page.evaluate(() => window.__workspaceFixture.navigate('/settings/display'))
    await expect(screen.getByRole('radio', { name: 'tmux', exact: true })).toBeChecked()
    await page.evaluate(() => window.__workspaceFixture.navigate('/sessions/chat-2'))
    await expect(shell).toBeVisible({ timeout: 15000 })
    await expect(page.locator('[data-pane-id][data-session-id="chat-2"] [data-testid="rich-composer-input"]')).toHaveText('Keep my tmux draft')
    expect(await page.evaluate(() => Array.from(document.querySelectorAll('[data-pane-id][data-session-id]')).map(n => n.getAttribute('data-pane-id')))).toEqual(paneIds)
    await page.reload()
    await expect(shell).toBeVisible({ timeout: 15000 })
    await expect(page.locator('[data-pane-id][data-session-id="chat-2"] [data-testid="rich-composer-input"]')).toHaveText('Keep my tmux draft')
    await page.evaluate(() => window.__workspaceFixture.navigate('/sessions/chat-2'))
    await page.evaluate(() => window.__workspaceFixture.navigate('/sessions/new'))
    await expect(shell).toBeHidden()
    await page.evaluate(() => window.__workspaceFixture.back())
    await expect(shell).toBeVisible({ timeout: 15000 })
    await page.evaluate(() => window.__workspaceFixture.navigate('/sessions/chat-1'))
    await expect(page.locator('[data-pane-id][data-session-id="chat-1"]')).toHaveAttribute('data-focused', 'true')
    await page.evaluate(() => window.__workspaceFixture.back())
    await expect(page.locator('[data-pane-id][data-session-id="chat-2"]')).toHaveAttribute('data-focused', 'true')
    await page.evaluate(() => window.__workspaceFixture.forward())
    await expect(page.locator('[data-pane-id][data-session-id="chat-1"]')).toHaveAttribute('data-focused', 'true')
    await page.evaluate(() => window.__workspaceFixture.navigate('/settings/display'))
    await screen.getByRole('radio', { name: 'Single conversation', exact: true }).check()
    await page.evaluate(() => window.__workspaceFixture.navigate('/sessions/chat-1'))
    await expect(shell).toHaveCount(0)
    // Old links must not override an explicit ordinary-mode choice.
    await page.evaluate(() => window.__workspaceFixture.navigate('/sessions/workspace'))
    await expect(shell).toHaveCount(0)
})
