import { expect, test } from '@playwright/test'

test('shares the complete turn across evicted pages without replacing the reader window', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?shareLongTurn=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
    await page.waitForTimeout(2000)
    expect(await page.evaluate(() => window.__probe.windowState().messageCount)).toBe(200)
    await expect(page.getByText('Export this complete long turn', { exact: true })).toHaveCount(0)
    const before = await page.evaluate(() => window.__probe.windowState())
    await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
    await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    await expect(dialog.getByText('Export this complete long turn', { exact: true })).toHaveCount(1)
    await expect(dialog.getByText('Export passage 602: complete history content.', { exact: true })).toHaveCount(1)
    await expect(dialog.getByText('Export passage 1199: complete history content.', { exact: true })).toHaveCount(1)
    await expect(dialog.getByText('Fixture message 1200', { exact: true })).toHaveCount(0)
    await expect(dialog.locator('p').filter({ hasText: /^Export passage \d+: complete history content\.$/ })).toHaveCount(598)
    expect(await page.evaluate(() => window.__probe.windowState())).toEqual(before)
    const requests = await page.evaluate(() => window.__probe.requests)
    expect(requests.filter(r => r.direction === 'context')).toHaveLength(1)
    expect(requests.filter(r => r.direction === 'before').length).toBeGreaterThan(0)
    expect(requests.filter(r => r.direction === 'after').length).toBeGreaterThan(0)
    expect(requests.every(r => (r.limit ?? 200) <= 200)).toBe(true)
    await dialog.getByRole('button', { name: 'Close', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await expect(page.getByText('Export this complete long turn', { exact: true })).toHaveCount(0)
    expect(await page.locator('[data-hapi-virtual-message]').count()).toBeLessThanOrEqual(40)
})

test('cancelling a held complete-turn read prevents a late preview', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?shareLongTurn=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
    await page.waitForTimeout(2000)
    await page.evaluate(() => window.__probe.holdContext())
    await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
    await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
    await expect(page.getByText('Preparing the complete turn…')).toBeVisible()
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.evaluate(() => window.__probe.releaseContext())
    await page.waitForTimeout(300)
    await expect(page.getByRole('dialog')).toHaveCount(0)
    expect(await page.evaluate(() => window.__probe.requests.filter(r => r.direction === 'before').length)).toBe(0)
})

test('switching sessions discards a held complete-turn read', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?shareLongTurn=1&readingAnchor=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
    await page.waitForTimeout(2000)
    await page.evaluate(() => window.__probe.holdContext())
    await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
    await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
    await expect(page.getByText('Preparing the complete turn…')).toBeVisible()
    await page.getByRole('button', { name: 'Switch to session B', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Switch to session A', exact: true })).toBeVisible()
    await page.evaluate(() => window.__probe.releaseContext())
    await page.waitForTimeout(300)
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByText('Preparing the complete turn…')).toHaveCount(0)
})

for (const failure of [false, true]) {
    test(`complete-turn export waits for an offscreen image and ${failure ? 'reports its failure' : 'retains it after capture unmounts'}`, async ({ page }) => {
        await page.goto(`/e2e-fixtures/history-load-fixture.html?shareLongTurn=1&shareSlowImage=1${failure ? '&shareImageFailure=1' : ''}`)
        await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
        await page.waitForTimeout(2000)
        expect(await page.evaluate(() => window.__probe.mediaReads)).toBe(0)
        await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
        await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
        if (failure) {
            await expect(page.getByRole('alert').getByText('Could not load this turn. Please try again.')).toBeVisible()
            await expect(page.getByRole('dialog')).toHaveCount(0)
        } else {
            const dialog = page.getByRole('dialog')
            await expect(dialog).toBeVisible()
            const image = dialog.getByRole('img', { name: 'share-image.svg', exact: true })
            await expect(image).toBeAttached()
            expect(await image.getAttribute('src')).toMatch(/^data:image\/svg\+xml/)
            await expect.poll(() => image.evaluate(element => (element as HTMLImageElement).naturalWidth)).toBe(80)
            await page.waitForTimeout(300)
            expect(await image.evaluate(element => (element as HTMLImageElement).complete)).toBe(true)
            await dialog.getByRole('button', { name: 'Close', exact: true }).click()
            await expect(image).toHaveCount(0)
        }
        expect(await page.evaluate(() => window.__probe.mediaReads)).toBe(1)
    })
}

for (const [query, message] of [
    ['shareContextDenied=1', 'Could not load this turn. Please try again.'],
    ['shareOversize=1', 'This turn is too large to share as one image (10,000 records or 8 MB).'],
]) {
    test(`complete-turn export reports ${query} without showing a partial preview`, async ({ page }) => {
        await page.goto(`/e2e-fixtures/history-load-fixture.html?shareLongTurn=1&${query}`)
        await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
        await page.waitForTimeout(2000)
        const before = await page.evaluate(() => window.__probe.windowState())
        await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
        await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
        await expect(page.getByRole('alert').getByText(message, { exact: true })).toBeVisible()
        await expect(page.getByRole('dialog')).toHaveCount(0)
        expect(await page.evaluate(() => window.__probe.windowState())).toEqual(before)
        await page.getByRole('button', { name: 'Cancel', exact: true }).click()
        await expect(page.getByRole('alert')).toHaveCount(0)
    })
}

test('cancelling while the offscreen image loads releases the capture and prevents a late preview', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?shareLongTurn=1&shareSlowImage=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
    await page.waitForTimeout(2000)
    await page.evaluate(() => window.__probe.holdMedia())
    await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
    await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
    await expect.poll(() => page.evaluate(() => window.__probe.mediaReads)).toBe(1)
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.evaluate(() => window.__probe.releaseMedia())
    await page.waitForTimeout(800)
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByText('Preparing the complete turn…')).toHaveCount(0)
    await expect(page.getByRole('alert')).toHaveCount(0)
})

test('history epoch change during export paging cancels the old capture', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?shareLongTurn=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
    await page.waitForTimeout(2000)
    await page.evaluate(() => window.__probe.holdBefore())
    await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
    await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
    await expect.poll(() => page.evaluate(() => window.__probe.requests.filter(r => r.direction === 'before').length)).toBeGreaterThan(0)
    await page.evaluate(() => window.__probe.remoteRewindTo(1100))
    await expect(page.getByText('Preparing the complete turn…')).toHaveCount(0)
    await page.evaluate(() => window.__probe.releaseBefore())
    await page.waitForTimeout(300)
    await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('downloads an image containing offscreen user, response and generated media', async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?shareLongTurn=1&shareSlowImage=1&shareMediaExport=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeInViewport()
    await page.waitForTimeout(2000)
    await page.getByText('Export passage 1199: complete history content.', { exact: true }).hover()
    await page.locator('[data-hapi-message-role="assistant"]').getByRole('button', { name: 'Share turn as image', exact: true }).last().click()
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByText('Export this complete long turn', { exact: true })).toBeVisible()
    await expect(dialog.getByRole('img', { name: 'share-image.svg', exact: true })).toBeAttached()
    const downloadPromise = page.waitForEvent('download')
    await dialog.getByRole('button', { name: 'Download', exact: true }).click()
    const download = await downloadPromise
    const path = testInfo.outputPath('complete-turn-media-export.png')
    await download.saveAs(path)
    const { readFile } = await import('node:fs/promises')
    const bytes = await readFile(path)
    expect(bytes.subarray(1, 4).toString()).toBe('PNG')
    expect(bytes.readUInt32BE(16)).toBe(1920)
    expect(bytes.readUInt32BE(20)).toBeGreaterThan(300)
    expect(bytes.byteLength).toBeGreaterThan(10_000)
})
