import { expect, test } from '@playwright/test'

test('finds a question beyond a thousand answers without paging bodies or moving the reader', async ({ page }, info) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?coldInitial=1&sparseOutline=1&outlineVirtual=1&outlineIndexReads=2')
    await expect(page.getByText(/^Sparse answer passage 1200:/)).toBeVisible()
    await page.waitForTimeout(400)
    const before = await page.evaluate(() => ({ state: window.__probe.windowState(), requests: [...window.__probe.requests],
        y: document.querySelector('.chat-scroll-y')!.scrollTop }))
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await expect(panel.getByRole('status')).toHaveText('Finding earlier questions…')
    await expect(panel.getByText('No questions in this conversation')).toHaveCount(0)
    const question = panel.getByRole('button', { name: /Fixture message 1$/ })
    await expect(question).toBeVisible()
    const after = await page.evaluate(() => ({ state: window.__probe.windowState(), requests: [...window.__probe.requests],
        y: document.querySelector('.chat-scroll-y')!.scrollTop }))
    expect(after.state.oldestSeq).toBe(before.state.oldestSeq)
    expect(after.state.messageCount).toBe(before.state.messageCount)
    expect(after.y).toBeCloseTo(before.y, 0)
    expect(after.requests.slice(before.requests.length).map(row => row.direction)).toEqual(['outline', 'outline', 'outline'])
    await question.click()
    await expect(page.locator('#hapi-message-user-text\\:m-1')).toBeInViewport()
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'context').length)).toBe(1)
    const newest = await page.evaluate(() => window.__probe.windowState().newestSeq)
    await page.locator('.chat-scroll-y').evaluate(element => { element.scrollTop = element.scrollHeight })
    await expect.poll(() => page.evaluate(() => window.__probe.windowState().newestSeq)).toBeGreaterThan(newest!)
    await page.getByRole('button', { name: 'Scroll to bottom', exact: true }).click()
    await expect(page.getByText(/^Sparse answer passage 1200:/)).toBeInViewport()
    await info.attach('outline-task-requests', { body: JSON.stringify({ before, after }), contentType: 'application/json' })
})

test('closing the directory stops indexing polls and reopening starts a fresh request', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?coldInitial=1&sparseOutline=1&outlineVirtual=1&outlineIndexReads=20&outlineDelay=200')
    await expect(page.getByText(/^Sparse answer passage 1200:/)).toBeVisible()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await expect.poll(() => page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'outline').length)).toBe(1)
    await panel.getByRole('button', { name: 'Close', exact: true }).click()
    await page.waitForTimeout(900)
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'outline').length)).toBe(1)
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    await expect.poll(() => page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'outline').length)).toBe(2)
    await expect(panel.getByRole('status')).toHaveText('Finding earlier questions…')
})

test('revoked directory access removes labels and does not retry on reopen', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?coldInitial=1&outlineVirtual=1&directoryDenied=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await expect(panel.getByRole('alert')).toContainText('directory forbidden')
    await expect(panel.locator('[data-outline-id]')).toHaveCount(0)
    await panel.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    await page.waitForTimeout(700)
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'outline').length)).toBe(1)
    await expect(panel.locator('[data-outline-id]')).toHaveCount(0)
})

test('an epoch reset with a failed refresh hides stale labels and can retry', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?coldInitial=1&outlineVirtual=1&outlineEpochReset=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect(panel.getByRole('alert')).toContainText('reset refresh failed')
    await expect(panel.locator('[data-outline-id]')).toHaveCount(0)
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect.poll(() => page.evaluate(() => window.__probe.windowState().newestSeq)).toBe(1000)
    await expect(panel.getByRole('alert')).toHaveCount(0)
    await panel.getByRole('searchbox', { name: 'Search outline items' }).fill('Fixture message 1200')
    await expect(panel.locator('[data-outline-id]')).toHaveCount(0)
})

test('metadata pages survive reopening while a fresh cursor chain bridges cached labels', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?coldInitial=1&outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '100')
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '200')
    await panel.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    await expect(panel.getByRole('button', { name: 'Load earlier', exact: true })).toBeEnabled()
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '300')
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'outline').map(row => row.beforeSeq))).toEqual([null, 1101, null, 1101, 1001])
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'before' || row.direction === 'context'))).toEqual([])
    expect(await page.evaluate(() => window.__probe.windowState().oldestSeq)).toBe(1181)
})


test('reopening after two hundred remote questions bridges the new-head gap before exhaustion', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?coldInitial=1&outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '100')
    await panel.getByRole('button', { name: 'Close', exact: true }).click()
    const before = await page.evaluate(() => window.__probe.windowState())
    await page.evaluate(() => { for (let i = 0; i < 200; i++) window.__probe.appendRemoteMessage(false) })
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '200')
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '300')
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'outline').at(-1)?.beforeSeq)).toBe(1301)
    for (let i = 0; i < 12 && await panel.getByRole('button', { name: 'Load earlier', exact: true }).count(); i++) {
        await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
        await expect(panel.getByRole('button', { name: 'Loading…', exact: true })).toHaveCount(0)
    }
    await expect(panel.getByRole('button', { name: 'Load earlier', exact: true })).toHaveCount(0)
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '1400')
    expect(await page.evaluate(() => window.__probe.windowState())).toEqual(before)
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'before' || row.direction === 'context'))).toEqual([])
    await panel.getByRole('searchbox', { name: 'Search outline items' }).fill('Fixture message 1250')
    await panel.getByRole('button', { name: /Fixture message 1250$/ }).click()
    await expect(page.getByText('Fixture message 1250', { exact: true })).toBeInViewport()
})

test('retrying a failed earlier metadata page preserves its cursor and the reading position', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?coldInitial=1&outlineVirtual=1&failOutline=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    const before = await page.locator('.chat-scroll-y').evaluate(element => element.scrollTop)
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '100')
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect(panel.getByRole('alert')).toContainText('outline page failed')
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect(panel.getByRole('alert')).toHaveCount(0)
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '200')
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'outline').map(row => row.beforeSeq))).toEqual([null, 1101, 1101])
    expect(await page.locator('.chat-scroll-y').evaluate(element => element.scrollTop)).toBeCloseTo(before, 0)
})

test('one earlier action adds earlier entries when metadata overlaps the warm reader', async ({ page }) => {
    await page.goto('/e2e-fixtures/history-load-fixture.html?outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline' })
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '200')
    await panel.getByRole('button', { name: 'Load earlier', exact: true }).click()
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '300')
    await expect(panel.getByRole('button', { name: /Fixture message 901$/ })).toBeVisible()
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'before'))).toEqual([])
})
