import { expect, test } from '@playwright/test'
import { loadDirectoryThrough } from './helpers/history-outline'


test('a long directory stays bounded, supports native scrolling and searches unloaded DOM entries', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.waitForTimeout(2000)
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline', exact: true })
    const list = panel.locator('[data-outline-count]')
    for (const oldest of [801, 601, 401, 201, 1]) {
        await loadDirectoryThrough(page, oldest)
        await expect(panel.getByRole('button', { name: new RegExp(`Fixture message ${oldest}$`) })).toBeVisible()
    }
    await expect(list).toHaveAttribute('data-outline-count', '1200')
    expect(await list.locator('[data-outline-id]').count()).toBeLessThan(24)
    const before = await page.evaluate(() => ({ oldest: window.__probe.windowState().oldestSeq, reads: window.__probe.requests.length }))
    const box = (await list.boundingBox())!
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
    await page.mouse.wheel(0, 5000)
    await expect.poll(() => list.evaluate(element => element.scrollTop)).toBeGreaterThan(4000)
    expect(await list.locator('[data-outline-id]').count()).toBeLessThan(24)
    await panel.getByRole('searchbox', { name: 'Search outline items' }).fill('Fixture message 700')
    await expect(panel.getByRole('button', { name: /Fixture message 700$/ })).toBeVisible()
    await panel.getByRole('button', { name: /Fixture message 700$/ }).click()
    await expect(panel).toHaveCount(0)
    await expect(page.getByText('Fixture message 700', { exact: true })).toBeInViewport({ ratio: 0.9 })
    expect(await page.evaluate(() => window.__probe.requests.filter(row => row.direction === 'context').length)).toBe(1)
    // Reader prefetch may start after navigation; directory loading itself
    // must not have fetched transcript pages.
    expect(await page.evaluate(count => window.__probe.requests.slice(0, count).filter(row => row.direction === 'before' || row.direction === 'context'), before.reads)).toEqual([])
    expect(before.oldest).toBeGreaterThan(700)
})

test('keyboard navigation reaches virtual directory entries and search resets its scroll position', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.waitForTimeout(2000)
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline', exact: true })
    await loadDirectoryThrough(page, 801)
    const first = panel.getByRole('button', { name: /Fixture message 801$/ })
    await first.focus()
    await first.press('End')
    const last = panel.getByRole('button', { name: /Fixture message 1200$/ })
    await expect(last).toBeFocused()
    await expect(last).toBeInViewport()
    await last.press('Home')
    await expect(first).toBeFocused()
    await expect(first).toBeInViewport()
    await first.press('PageDown')
    await expect.poll(() => panel.locator('[data-outline-count]').evaluate(element => element.scrollTop)).toBeGreaterThan(0)
    await panel.getByRole('searchbox', { name: 'Search outline items' }).fill('Fixture message 1000')
    await expect(panel.getByRole('button', { name: /Fixture message 1000$/ })).toBeVisible()
    await panel.getByRole('searchbox', { name: 'Search outline items' }).fill('')
    await expect(first).toBeVisible()
    expect(await panel.locator('[data-outline-id]').count()).toBeLessThan(24)
})

test('loading earlier from the end of a long directory reveals the new starting entries', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.waitForTimeout(2000)
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline', exact: true })
    await loadDirectoryThrough(page, 801)
    const first = panel.getByRole('button', { name: /Fixture message 801$/ })
    await first.focus()
    await first.press('End')
    await expect(panel.getByRole('button', { name: /Fixture message 1200$/ })).toBeInViewport()
    await loadDirectoryThrough(page, 601)
    await expect(panel.getByRole('button', { name: /Fixture message 601$/ })).toBeInViewport()
    await expect(panel.locator('[data-outline-count]')).toHaveAttribute('data-outline-count', '600')
    expect(await panel.locator('[data-outline-id]').count()).toBeLessThan(24)
})

test('a history reset removing the focused directory item returns focus to search', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.waitForTimeout(2000)
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline', exact: true })
    await panel.getByRole('button', { name: /Fixture message 1001$/ }).focus()
    await page.evaluate(() => window.__probe.remoteRewindTo(1000))
    await expect(panel.getByRole('button', { name: /Fixture message 1001$/ })).toHaveCount(0)
    await expect(panel.getByRole('searchbox', { name: 'Search outline items' })).toBeFocused()
    await expect(panel.getByRole('button', { name: /Fixture message 801$/ })).toBeVisible()
})

test('removing an explicitly blurred directory item does not move focus back into the directory', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/e2e-fixtures/history-load-fixture.html?outlineVirtual=1')
    await expect(page.getByText('Fixture message 1200', { exact: true })).toBeVisible()
    await page.waitForTimeout(2000)
    await page.getByRole('button', { name: 'Open conversation outline', exact: true }).click()
    const panel = page.getByRole('complementary', { name: 'Outline', exact: true })
    const item = panel.getByRole('button', { name: /Fixture message 1001$/ })
    await item.focus()
    await item.evaluate(element => element.blur())
    expect(await page.evaluate(() => document.activeElement === document.body)).toBe(true)
    await page.evaluate(() => window.__probe.remoteRewindTo(1000))
    await expect(item).toHaveCount(0)
    await expect(panel.getByRole('button', { name: /Fixture message 801$/ })).toBeVisible()
    await expect(panel.getByRole('searchbox', { name: 'Search outline items' })).not.toBeFocused()
    expect(await page.evaluate(() => document.activeElement === document.body)).toBe(true)
})
