import { expect, test } from '@playwright/test'

for (const width of [390, 1440]) {
    test(`renders an isolated interactive Windows HTML report and keeps its pane state at ${width}px`, async ({ page }) => {
        await page.setViewportSize({ width, height: 844 })
        const leaked: string[] = []
        page.on('request', request => { if (/example\.com|file:\/\//.test(request.url())) leaked.push(request.url()) })
        await page.goto('/e2e-fixtures/workspace-fixture.html?panes=1&documents=1&htmlDocument=1')
        const surface = page.locator('.document-surface').first()
        await expect(surface.locator('.document-html')).toHaveAttribute('data-html-state', 'ready')
        const frame = page.frameLocator('.document-html-frame').first()
        await expect(frame.getByRole('heading', { name: '全联系人深读 · 阅读台账' })).toBeVisible()
        await expect(frame.locator('body')).toHaveAttribute('data-isolated', 'true')
        await expect(frame.locator('h1')).toHaveCSS('font-size', '22px')
        await expect.poll(() => frame.getByAltText('报告标记').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(32)
        const starts = () => frame.locator('body').evaluate(() => (window as unknown as { reportStarts: number }).reportStarts)
        await expect.poll(starts).toBe(1)
        const filter = frame.getByRole('textbox', { name: '查找联系人' })
        await filter.fill('联系人 12')
        await expect(frame.locator('tbody tr:visible')).toHaveCount(1)
        await frame.getByText('顺序阅读原文').nth(11).click()
        await expect(frame.locator('tbody tr').nth(11).locator('details')).toHaveAttribute('open', '')

        await surface.getByRole('button', { name: 'Source', exact: true }).click()
        await expect(surface.locator('.cm-content')).toContainText('<!doctype html>')
        await surface.getByRole('button', { name: 'Preview', exact: true }).click()
        await expect(filter).toHaveValue('联系人 12')
        await expect.poll(starts).toBe(1)
        const htmlFrame = await page.locator('.document-html-frame').first().contentFrame().locator('body').evaluate(() => window.name = 'kept-html-frame')
        expect(htmlFrame).toBe('kept-html-frame')

        if (width < 640) await page.getByRole('button', { name: 'P1', exact: true }).click()
        else {
            await page.getByTestId('rich-composer-input').first().click()
            await page.keyboard.press('Control+b'); await page.keyboard.press('z')
        }
        await expect(surface).not.toBeVisible()
        if (width < 640) await page.getByRole('button', { name: 'P2', exact: true }).click()
        else { await page.keyboard.press('Control+b'); await page.keyboard.press('z') }
        await expect(filter).toHaveValue('联系人 12')
        expect(await frame.locator('body').evaluate(() => window.name)).toBe('kept-html-frame')
        await expect(frame.locator('tbody tr').nth(11).locator('details')).toHaveAttribute('open', '')
        await filter.fill('')
        await frame.getByRole('link', { name: '跳到末尾' }).click()
        await expect(frame.getByText('阅读完毕')).toBeInViewport()
        expect(await starts()).toBe(1)
        expect(leaked).toEqual([])
        expect(await page.evaluate(() => window.__workspaceFixture.unhandled)).toEqual([])
    })
}

test('blocks report network resources, nested frames and parent storage access', async ({ page }) => {
    const requests: string[] = []
    // Abort any leaked request so a failing test never contacts the external host.
    await page.route('https://example.com/**', route => { requests.push(route.request().url()); return route.abort() })
    await page.goto('/e2e-fixtures/workspace-fixture.html?panes=1&documents=1&htmlDocument=1&htmlIsolation=1')
    const surface = page.locator('.document-surface').first()
    await expect(surface.locator('.document-html')).toHaveAttribute('data-html-state', 'ready')
    const frame = page.frameLocator('.document-html-frame').first()
    await expect(frame.getByRole('heading', { name: '隔离边界测试' })).toBeVisible()
    await expect(frame.locator('body')).toHaveAttribute('data-network', 'blocked')
    await expect(frame.locator('body')).toHaveAttribute('data-isolated', 'true')
    await expect(frame.locator('iframe')).toHaveCount(0)
    await expect(surface).toContainText('Some resources could not be loaded')
    expect(requests).toEqual([])
})

test('opens a file URL beside the report on its original machine and session', async ({ page }) => {
    await page.goto('/e2e-fixtures/workspace-fixture.html?panes=1&documents=1&htmlDocument=1')
    const frame = page.frameLocator('.document-html-frame').first()
    await frame.getByText('顺序阅读原文').first().click()
    await frame.getByRole('link', { name: '原文 1', exact: true }).first().click()
    const text = page.locator('.document-surface').filter({ has: page.getByText('原文 1.txt', { exact: true }) })
    await expect(text.locator('.cm-content')).toContainText('原文文档已从 Lis-iMac 打开。')
    const state = await page.evaluate(() => JSON.stringify(localStorage))
    expect(state).toContain('machine-lis-imac')
    expect(state).toContain('原文 1.txt')
    const reads = await page.evaluate(() => window.__workspaceFixture.requests.filter(url => url.includes('/file?')))
    expect(reads.every(url => url.includes('/sessions/chat-1/'))).toBe(true)
    expect(reads.some(url => decodeURIComponent(url.replaceAll('+', ' ')).includes('packets\\原文 1.txt'))).toBe(true)
})

test('references rendered text without sending and keeps mixed newline files previewable', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 960 })
    await page.goto('/e2e-fixtures/workspace-fixture.html?panes=1&documents=1&htmlDocument=1&htmlMixed=1')
    const surface = page.locator('.document-surface').first()
    const frame = page.frameLocator('.document-html-frame').first()
    await expect(frame.getByRole('heading')).toBeVisible()
    await expect(surface).not.toContainText('Mixed line endings')
    await frame.locator('#quote').evaluate(element => {
        const range = document.createRange(); range.selectNodeContents(element)
        const selection = getSelection()!; selection.removeAllRanges(); selection.addRange(range)
        document.dispatchEvent(new Event('selectionchange'))
    })
    await expect(surface.locator('.document-selection')).toContainText('这是可选中并请求修改的报告正文。')
    await surface.getByRole('button', { name: 'Reference selection', exact: true }).click()
    const draft = page.getByTestId('document-reference-drafts')
    await expect(draft).toContainText('阅读台账.html · Preview')
    await draft.locator('summary').click()
    await expect(draft.locator('pre')).toContainText('这是可选中并请求修改的报告正文。')
    expect(await page.evaluate(() => window.__workspaceFixture.sends.length)).toBe(0)
    const composer = page.getByTestId('rich-composer-input').first()
    await composer.fill('请改进这段说明'); await composer.press('Enter')
    await expect.poll(() => page.evaluate(() => window.__workspaceFixture.sends.length)).toBe(1)
    const sent = await page.evaluate(() => window.__workspaceFixture.sends[0])
    expect(sent.sessionId).toBe('chat-1')
    expect(sent.text).toContain('rendered HTML; DOM range')
    expect(sent.text).toContain('Source: \\\\?\\C:\\Users\\fixture\\report\\阅读台账.html')
    expect(sent.text).not.toContain('LF-normalized')
    await surface.getByRole('button', { name: 'Source', exact: true }).click()
    await expect(surface).toContainText('Mixed line endings')
    await expect(surface.locator('.cm-content')).toHaveAttribute('contenteditable', 'false')
})

test('edits HTML source, updates preview explicitly and restores view state after a document reload', async ({ page }) => {
    await page.goto('/e2e-fixtures/workspace-fixture.html?panes=1&documents=1&htmlDocument=1')
    const surface = page.locator('.document-surface').first()
    await expect(surface.locator('.document-html')).toHaveAttribute('data-html-state', 'ready')
    await surface.getByRole('button', { name: 'Source', exact: true }).click()
    const editor = surface.locator('.cm-content')
    await editor.click(); await editor.press('Control+End'); await editor.pressSequentially('<p id="edited">已修改报告</p>')
    await surface.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(surface.locator('.document-status')).toHaveText('Saved')
    await surface.getByRole('button', { name: 'Preview', exact: true }).click()
    const frame = page.frameLocator('.document-html-frame').first()
    await expect(frame.getByText('已修改报告')).toBeAttached()
    await frame.getByRole('textbox', { name: '查找联系人' }).fill('联系人 12')
    await frame.getByText('顺序阅读原文').nth(11).click()
    await expect.poll(() => frame.locator('tbody tr:visible').count()).toBe(1)
    // Wait for the state publication, rather than adding a timer to the implementation.
    await frame.locator('body').evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
    await surface.getByRole('button', { name: 'Reload', exact: true }).click()
    await expect(surface.locator('.document-html')).toHaveAttribute('data-html-state', 'ready')
    await expect(frame.getByRole('textbox', { name: '查找联系人' })).toHaveValue('联系人 12')
    await expect(frame.locator('tbody tr').nth(11).locator('details')).toHaveAttribute('open', '')
    expect(await page.evaluate(() => window.__workspaceFixture.fileWrites.length)).toBe(1)
})
