import { expect, test, type Page } from '@playwright/test'

const pane = (page: Page, session: string) => page.locator(`[data-pane-id][data-session-id="${session}"]`)
const editor = (page: Page, session: string) => pane(page, session).locator('[data-testid="rich-composer-input"]')
const row = (page: Page, title: string) => page.locator('.app-session-sidebar-frame .session-list-item').filter({ has: page.getByText(title, { exact: true }) })

for (const [placement, horizontal] of [['Open in new pane to the right', true], ['Open in new pane below', false]] as const) {
    test(`right-click waits for an action, then ${placement.toLowerCase()} preserves the old chat`, async ({ page }) => {
        await page.setViewportSize({ width: 1440, height: 900 })
        await page.goto('/e2e-fixtures/workspace-fixture.html?split')
        await expect(page.locator('[data-chat-presented=true]')).toHaveCount(2)
        await editor(page, 'chat-2').fill('Keep my draft while opening another pane')
        await page.evaluate(() => {
            ;(window as any).__contextReader = document.querySelector('[data-pane-id][data-session-id="chat-2"] .chat-scroll-y')
        })
        const target = row(page, '工作区交互设计')
        await target.click({ button: 'right' })
        await expect(page.getByRole('menu')).toBeVisible()
        await expect(pane(page, 'chat-2')).toHaveAttribute('data-focused', 'true')
        await expect(pane(page, 'chat-3')).toHaveCount(0)
        await expect(page.locator('[data-pane-id]:visible')).toHaveCount(2)
        await expect(page.getByRole('menuitem', { name: 'Open in current pane', exact: true })).toBeVisible()
        await page.keyboard.press('Escape')
        await expect(page.getByRole('menu')).toHaveCount(0)
        await expect(pane(page, 'chat-2')).toHaveAttribute('data-focused', 'true')
        // Keyboard users can open the same menu without selecting first.
        await target.focus()
        await page.keyboard.press('Shift+F10')
        await expect(page.getByRole('menu')).toBeVisible()
        await page.getByRole('menuitem', { name: placement, exact: true }).click()
        await expect(page.getByRole('menu')).toHaveCount(0)
        await expect(page.locator('[data-pane-id]:visible')).toHaveCount(3)
        await expect(pane(page, 'chat-3')).toHaveAttribute('data-focused', 'true')
        await expect(pane(page, 'chat-3').locator('[data-chat-presented=true]')).toBeVisible()
        const old = (await pane(page, 'chat-2').boundingBox())!, added = (await pane(page, 'chat-3').boundingBox())!
        if (horizontal) expect(added.x).toBeGreaterThanOrEqual(old.x + old.width)
        else expect(added.y).toBeGreaterThanOrEqual(old.y + old.height)
        await expect(editor(page, 'chat-2')).toHaveText('Keep my draft while opening another pane')
        expect(await page.evaluate(() => document.querySelector('[data-pane-id][data-session-id="chat-2"] .chat-scroll-y') === (window as any).__contextReader)).toBe(true)
        expect(await page.evaluate(() => window.__workspaceFixture.sends)).toEqual([])
        await page.reload()
        await expect(page.locator('[data-pane-id]:visible')).toHaveCount(3)
        await expect(editor(page, 'chat-2')).toHaveText('Keep my draft while opening another pane')
    })
}

test('explicit current-pane opening replaces only the focused pane and plain left-click still selects', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/e2e-fixtures/workspace-fixture.html?split')
    await row(page, '工作区交互设计').click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Open in current pane', exact: true }).click()
    await expect(page.locator('[data-pane-id]:visible')).toHaveCount(2)
    await expect(pane(page, 'chat-1')).toBeVisible()
    await expect(pane(page, 'chat-3')).toBeVisible()
    await expect(pane(page, 'chat-2')).toHaveCount(0)
    await row(page, '发布检查').click()
    await expect(pane(page, 'chat-4')).toBeVisible()
    await expect(pane(page, 'chat-3')).toHaveCount(0)
})

test('opens beside a single conversation and focuses already-open chats without duplicating them', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/e2e-fixtures/workspace-fixture.html?single')
    await expect(page.locator('[data-chat-presented=true]')).toBeVisible()
    await row(page, '工作区交互设计').click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Open in new pane to the right', exact: true }).click()
    await expect(page.locator('[data-pane-id]:visible')).toHaveCount(2)
    await expect(pane(page, 'chat-1')).toBeVisible()
    await expect(pane(page, 'chat-3')).toBeVisible()
    await row(page, '历史阅读优化').click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Open in new pane below', exact: true }).click()
    await expect(pane(page, 'chat-1')).toHaveAttribute('data-focused', 'true')
    await expect(page.locator('[data-pane-id]:visible')).toHaveCount(2)
    expect(await page.evaluate(() => window.__workspaceFixture.sends)).toEqual([])
})
