import { expect, test, type Locator } from '@playwright/test'

const input = (root: Locator) => root.locator('[contenteditable]:not([contenteditable="false"])')
test.use({ viewport: { width: 1600, height: 960 } })

for (const eventFirst of [false, true]) test(`keeps attachment ownership and the neighboring Goal draft when resume changes the pane identity${eventFirst ? ' before its HTTP response' : ''}`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/e2e-fixtures/workspace-fixture.html?split&mixed&controls', { waitUntil: 'domcontentloaded' })
    const source = page.locator('[data-pane-id][data-session-id="chat-2"]')
    const neighbor = page.locator('[data-pane-id][data-session-id="chat-1"]')
    const target = page.locator('[data-pane-id][data-session-id="chat-2-resumed"]')
    await expect(source.locator('[data-chat-presented=true]')).toBeVisible()
    await expect(neighbor.locator('[data-chat-presented=true]')).toBeVisible()
    const originalPane = await source.getAttribute('data-pane-id')
    await input(neighbor).fill('The neighboring chat stays independent')
    await input(source).fill('Read this file after resume')
    const picker = page.waitForEvent('filechooser')
    await source.getByRole('button', { name: 'Attach file', exact: true }).click()
    await (await picker).setFiles({ name: 'resume-notes.txt', mimeType: 'text/plain', buffer: Buffer.from('Keep this file with its resumed conversation.') })
    await expect.poll(() => page.evaluate(() => window.__workspaceFixture.uploads.filter(u => u.complete).length)).toBe(1)
    await page.evaluate(() => { window.__workspaceFixture.holdResume(); window.__workspaceFixture.archive('chat-2') })
    await expect(source.getByRole('button', { name: 'Goal controls', exact: true })).toBeDisabled()
    await expect(source.getByRole('button', { name: 'Send', exact: true })).toBeEnabled()
    await input(source).click()
    await page.keyboard.press('Enter')
    await expect.poll(() => page.evaluate(() => window.__workspaceFixture.resumes)).toEqual([{ source: 'chat-2', target: 'chat-2-resumed' }])
    await neighbor.getByRole('button', { name: 'Goal controls', exact: true }).click()
    await page.getByRole('button', { name: 'Set a goal', exact: true }).click()
    const objective = page.getByRole('textbox', { name: 'Goal', exact: true })
    await objective.fill('Keep this goal on the neighboring conversation')
    if (eventFirst) {
        await page.evaluate(() => window.__workspaceFixture.publishSupersession())
        // The notification must not mount an empty target before the in-flight
        // send has transferred its submitted draft.
        await expect(source).toHaveAttribute('data-pane-id', originalPane!)
    }
    await page.evaluate(() => window.__workspaceFixture.finishResume())
    await expect(target).toHaveAttribute('data-pane-id', originalPane!)
    await expect(objective).toHaveValue('Keep this goal on the neighboring conversation')
    await expect(objective).toBeFocused()
    await expect(input(target)).toHaveText('Read this file after resume')
    await expect(target.getByText('resume-notes.txt', { exact: true })).toBeVisible()
    await expect.poll(() => page.evaluate(() => window.__workspaceFixture.uploads.filter(u => u.sessionId === 'chat-2-resumed' && u.complete).length)).toBe(1)
    expect(await page.evaluate(() => window.__workspaceFixture.sends)).toEqual([])
    await page.getByRole('button', { name: 'Save goal', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    expect(await page.evaluate(() => window.__workspaceFixture.goals)).toEqual([{ sessionId: 'chat-1', action: 'set', objective: 'Keep this goal on the neighboring conversation' }])
    await expect(input(neighbor)).toHaveText('The neighboring chat stays independent')
    await expect(neighbor.getByText('resume-notes.txt', { exact: true })).toHaveCount(0)
    await input(target).click()
    await page.keyboard.press('Enter')
    await expect.poll(() => page.evaluate(() => window.__workspaceFixture.sends.length)).toBe(1)
    const sent = await page.evaluate(() => window.__workspaceFixture.sends[0])
    expect(sent.sessionId).toBe('chat-2-resumed')
    expect(sent.text).toBe('Read this file after resume')
    const uploaded = await page.evaluate(() => window.__workspaceFixture.uploads.find(u => u.sessionId === 'chat-2-resumed')!)
    expect((sent as any).attachments).toEqual([expect.objectContaining({ path: uploaded.path })])
    expect(await page.evaluate(() => window.__workspaceFixture.unhandled)).toEqual([])
    expect(errors).toEqual([])
})
